# SPDX-License-Identifier: Apache-2.0

name: TruffleHog

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run TruffleHog
        uses: sentenz/actions/trufflehog@e59be3f004f11bc57b50715d04baa6fe139487bb
        with:
          path: ./
          extra-args: --debug
